# Generated by Django 5.2.7 on 2025-10-07 01:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posteo',
            options={'ordering': ['-created'], 'verbose_name': 'Posteo', 'verbose_name_plural': 'Posteos'},
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='posteo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen opcional para la noticia', null=True, upload_to='noticias/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='posteo',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
